services:
  server:
    build: .
    image: "php-tank"
    container_name: "php-tank"
    ports:
      - "8088:8000"
    volumes:
      - ./src:/var/www/html/
  mongodb:
    image: "mongo:7.0"
    container_name: "mongodb"
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: "redis:7-alpine"
    container_name: "redis"
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
